//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
//

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace com.vis_dhs.test {

    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmployerWebServiceV18Soap", Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmployerWebServiceV18Wse : Microsoft.Web.Services2.WebServicesClientProtocol {

        /// <remarks/>
        public EmployerWebServiceV18Wse() {
            this.Url = "https://test.vis-dhs.com/WebService/EmployerWebServiceV18.asmx";
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpInitBPVerif", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpInitVerfResp EmpInitBPVerif(
                    string ClientSftwrVer,
                    string LastName,
                    string FirstName,
                    string MiddleInitial,
                    string MaidenName,
                    string SSNNumber,
                    System.DateTime BirthDate,
                    System.DateTime HireDate,
                    int CitizenshipStatus,
                    string AlienNumber,
                    string I94Number,
                    string CardNbr,
                    string PassPortNumber,
                    string VisaNumber,
                    int DocumentID,
                    System.DateTime DocExpDate,
                    string SubmittingOfficial,
                    string SubmittersPhoneNbr,
                    string UserField) {
            object[] results = this.Invoke("EmpInitBPVerif", new object[] {
                        ClientSftwrVer,
                        LastName,
                        FirstName,
                        MiddleInitial,
                        MaidenName,
                        SSNNumber,
                        BirthDate,
                        HireDate,
                        CitizenshipStatus,
                        AlienNumber,
                        I94Number,
                        CardNbr,
                        PassPortNumber,
                        VisaNumber,
                        DocumentID,
                        DocExpDate,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        UserField});
            return ((EmpInitVerfResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpInitBPVerif(
                    string ClientSftwrVer,
                    string LastName,
                    string FirstName,
                    string MiddleInitial,
                    string MaidenName,
                    string SSNNumber,
                    System.DateTime BirthDate,
                    System.DateTime HireDate,
                    int CitizenshipStatus,
                    string AlienNumber,
                    string I94Number,
                    string CardNbr,
                    string PassPortNumber,
                    string VisaNumber,
                    int DocumentID,
                    System.DateTime DocExpDate,
                    string SubmittingOfficial,
                    string SubmittersPhoneNbr,
                    string UserField,
                    System.AsyncCallback callback,
                    object asyncState) {
            return this.BeginInvoke("EmpInitBPVerif", new object[] {
                        ClientSftwrVer,
                        LastName,
                        FirstName,
                        MiddleInitial,
                        MaidenName,
                        SSNNumber,
                        BirthDate,
                        HireDate,
                        CitizenshipStatus,
                        AlienNumber,
                        I94Number,
                        CardNbr,
                        PassPortNumber,
                        VisaNumber,
                        DocumentID,
                        DocExpDate,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        UserField}, callback, asyncState);
        }

        /// <remarks/>
        public EmpInitVerfResp EndEmpInitBPVerif(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpInitVerfResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpInitDABPVerif", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpInitVerfResp EmpInitDABPVerif(
                    int ClientCompanyId,
                    string ClientSftwrVer,
                    string LastName,
                    string FirstName,
                    string MiddleInitial,
                    string MaidenName,
                    string SSNNumber,
                    System.DateTime BirthDate,
                    System.DateTime HireDate,
                    int CitizenshipStatus,
                    string AlienNumber,
                    string I94Number,
                    string CardNbr,
                    string PassPortNumber,
                    string VisaNumber,
                    int DocumentID,
                    System.DateTime DocExpDate,
                    string SubmittingOfficial,
                    string SubmittersPhoneNbr,
                    string UserField) {
            object[] results = this.Invoke("EmpInitDABPVerif", new object[] {
                        ClientCompanyId,
                        ClientSftwrVer,
                        LastName,
                        FirstName,
                        MiddleInitial,
                        MaidenName,
                        SSNNumber,
                        BirthDate,
                        HireDate,
                        CitizenshipStatus,
                        AlienNumber,
                        I94Number,
                        CardNbr,
                        PassPortNumber,
                        VisaNumber,
                        DocumentID,
                        DocExpDate,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        UserField});
            return ((EmpInitVerfResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpInitDABPVerif(
                    int ClientCompanyId,
                    string ClientSftwrVer,
                    string LastName,
                    string FirstName,
                    string MiddleInitial,
                    string MaidenName,
                    string SSNNumber,
                    System.DateTime BirthDate,
                    System.DateTime HireDate,
                    int CitizenshipStatus,
                    string AlienNumber,
                    string I94Number,
                    string CardNbr,
                    string PassPortNumber,
                    string VisaNumber,
                    int DocumentID,
                    System.DateTime DocExpDate,
                    string SubmittingOfficial,
                    string SubmittersPhoneNbr,
                    string UserField,
                    System.AsyncCallback callback,
                    object asyncState) {
            return this.BeginInvoke("EmpInitDABPVerif", new object[] {
                        ClientCompanyId,
                        ClientSftwrVer,
                        LastName,
                        FirstName,
                        MiddleInitial,
                        MaidenName,
                        SSNNumber,
                        BirthDate,
                        HireDate,
                        CitizenshipStatus,
                        AlienNumber,
                        I94Number,
                        CardNbr,
                        PassPortNumber,
                        VisaNumber,
                        DocumentID,
                        DocExpDate,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        UserField}, callback, asyncState);
        }

        /// <remarks/>
        public EmpInitVerfResp EndEmpInitDABPVerif(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpInitVerfResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpSubmitAdditVerif", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpSubmitAdditVerifResp EmpSubmitAdditVerif(string ClientSftwrVer, string CaseNbr, string SubmittingOfficial, string SubmittersPhoneNbr, string Comment) {
            object[] results = this.Invoke("EmpSubmitAdditVerif", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        Comment});
            return ((EmpSubmitAdditVerifResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpSubmitAdditVerif(string ClientSftwrVer, string CaseNbr, string SubmittingOfficial, string SubmittersPhoneNbr, string Comment, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpSubmitAdditVerif", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        Comment}, callback, asyncState);
        }

        /// <remarks/>
        public EmpSubmitAdditVerifResp EndEmpSubmitAdditVerif(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpSubmitAdditVerifResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpGetNextResolvedCaseNbrs", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpGetNextResolvedCaseNbrsResp EmpGetNextResolvedCaseNbrs(string ClientSftwrVer, string SearchType, string AcknowledgeFlg) {
            object[] results = this.Invoke("EmpGetNextResolvedCaseNbrs", new object[] {
                        ClientSftwrVer,
                        SearchType,
                        AcknowledgeFlg});
            return ((EmpGetNextResolvedCaseNbrsResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpGetNextResolvedCaseNbrs(string ClientSftwrVer, string SearchType, string AcknowledgeFlg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpGetNextResolvedCaseNbrs", new object[] {
                        ClientSftwrVer,
                        SearchType,
                        AcknowledgeFlg}, callback, asyncState);
        }

        /// <remarks/>
        public EmpGetNextResolvedCaseNbrsResp EndEmpGetNextResolvedCaseNbrs(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpGetNextResolvedCaseNbrsResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpAckReceiptOfResolvedCaseNbr", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpAckReceiptOfResolvedCaseNbrResp EmpAckReceiptOfResolvedCaseNbr(string ClientSftwrVer, string CaseNbr, string TypeOfCase) {
            object[] results = this.Invoke("EmpAckReceiptOfResolvedCaseNbr", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        TypeOfCase});
            return ((EmpAckReceiptOfResolvedCaseNbrResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpAckReceiptOfResolvedCaseNbr(string ClientSftwrVer, string CaseNbr, string TypeOfCase, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpAckReceiptOfResolvedCaseNbr", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        TypeOfCase}, callback, asyncState);
        }

        /// <remarks/>
        public EmpAckReceiptOfResolvedCaseNbrResp EndEmpAckReceiptOfResolvedCaseNbr(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpAckReceiptOfResolvedCaseNbrResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpCloseCase", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpCloseCaseResp EmpCloseCase(string ClientSftwrVer, string CaseNbr, string CloseStatus) {
            object[] results = this.Invoke("EmpCloseCase", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        CloseStatus});
            return ((EmpCloseCaseResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpCloseCase(string ClientSftwrVer, string CaseNbr, string CloseStatus, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpCloseCase", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        CloseStatus}, callback, asyncState);
        }

        /// <remarks/>
        public EmpCloseCaseResp EndEmpCloseCase(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpCloseCaseResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpSubSSAReferral", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpSubmitSSAReferralResp EmpSubSSAReferral(string ClientSftwrVer, string CaseNbr) {
            object[] results = this.Invoke("EmpSubSSAReferral", new object[] {
                        ClientSftwrVer,
                        CaseNbr});
            return ((EmpSubmitSSAReferralResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpSubSSAReferral(string ClientSftwrVer, string CaseNbr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpSubSSAReferral", new object[] {
                        ClientSftwrVer,
                        CaseNbr}, callback, asyncState);
        }

        /// <remarks/>
        public EmpSubmitSSAReferralResp EndEmpSubSSAReferral(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpSubmitSSAReferralResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpCpsVerifyConnection", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpCpsVerifyConnectionResp EmpCpsVerifyConnection() {
            object[] results = this.Invoke("EmpCpsVerifyConnection", new object[0]);
            return ((EmpCpsVerifyConnectionResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpCpsVerifyConnection(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpCpsVerifyConnection", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public EmpCpsVerifyConnectionResp EndEmpCpsVerifyConnection(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpCpsVerifyConnectionResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpSubDHSReferral", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpSubmitDHSReferralResp7 EmpSubDHSReferral(string ClientSftwrVer, string CaseNbr) {
            object[] results = this.Invoke("EmpSubDHSReferral", new object[] {
                        ClientSftwrVer,
                        CaseNbr});
            return ((EmpSubmitDHSReferralResp7)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpSubDHSReferral(string ClientSftwrVer, string CaseNbr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpSubDHSReferral", new object[] {
                        ClientSftwrVer,
                        CaseNbr}, callback, asyncState);
        }

        /// <remarks/>
        public EmpSubmitDHSReferralResp7 EndEmpSubDHSReferral(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpSubmitDHSReferralResp7)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/SetUserPassword", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetUserPasswordResp SetUserPassword(string NewPassword) {
            object[] results = this.Invoke("SetUserPassword", new object[] {
                        NewPassword});
            return ((SetUserPasswordResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSetUserPassword(string NewPassword, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetUserPassword", new object[] {
                        NewPassword}, callback, asyncState);
        }

        /// <remarks/>
        public SetUserPasswordResp EndSetUserPassword(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SetUserPasswordResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpSSAResubmittal", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpSSAResubmittalResp EmpSSAResubmittal(string ClientSftwrVer, string CaseNbr, string LastName, string FirstName, string MiddleNameInitial, string MaidenName, string SocialSecurityNbr, System.DateTime BirthDate) {
            object[] results = this.Invoke("EmpSSAResubmittal", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        LastName,
                        FirstName,
                        MiddleNameInitial,
                        MaidenName,
                        SocialSecurityNbr,
                        BirthDate});
            return ((EmpSSAResubmittalResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpSSAResubmittal(string ClientSftwrVer, string CaseNbr, string LastName, string FirstName, string MiddleNameInitial, string MaidenName, string SocialSecurityNbr, System.DateTime BirthDate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpSSAResubmittal", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        LastName,
                        FirstName,
                        MiddleNameInitial,
                        MaidenName,
                        SocialSecurityNbr,
                        BirthDate}, callback, asyncState);
        }

        /// <remarks/>
        public EmpSSAResubmittalResp EndEmpSSAResubmittal(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpSSAResubmittalResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpGetCaseDetails", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpGtCseDetailsResp7 EmpGetCaseDetails(string CaseNbr) {
            object[] results = this.Invoke("EmpGetCaseDetails", new object[] {
                        CaseNbr});
            return ((EmpGtCseDetailsResp7)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpGetCaseDetails(string CaseNbr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpGetCaseDetails", new object[] {
                        CaseNbr}, callback, asyncState);
        }

        /// <remarks/>
        public EmpGtCseDetailsResp7 EndEmpGetCaseDetails(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpGtCseDetailsResp7)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpGetCitizenshipStatusCodes", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpGetCitizenshipCodesResp EmpGetCitizenshipStatusCodes() {
            object[] results = this.Invoke("EmpGetCitizenshipStatusCodes", new object[0]);
            return ((EmpGetCitizenshipCodesResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpGetCitizenshipStatusCodes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpGetCitizenshipStatusCodes", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public EmpGetCitizenshipCodesResp EndEmpGetCitizenshipStatusCodes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpGetCitizenshipCodesResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpGetAvailableDocumentTypes", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpGetAvailableDocumentTypesResp EmpGetAvailableDocumentTypes(string CitizenshipCode) {
            object[] results = this.Invoke("EmpGetAvailableDocumentTypes", new object[] {
                        CitizenshipCode});
            return ((EmpGetAvailableDocumentTypesResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpGetAvailableDocumentTypes(string CitizenshipCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpGetAvailableDocumentTypes", new object[] {
                        CitizenshipCode}, callback, asyncState);
        }

        /// <remarks/>
        public EmpGetAvailableDocumentTypesResp EndEmpGetAvailableDocumentTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpGetAvailableDocumentTypesResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpGetAllDataFields", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpGetAllDataFieldsResp EmpGetAllDataFields(string CitizenshipCode, string DocId) {
            object[] results = this.Invoke("EmpGetAllDataFields", new object[] {
                        CitizenshipCode,
                        DocId});
            return ((EmpGetAllDataFieldsResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpGetAllDataFields(string CitizenshipCode, string DocId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpGetAllDataFields", new object[] {
                        CitizenshipCode,
                        DocId}, callback, asyncState);
        }

        /// <remarks/>
        public EmpGetAllDataFieldsResp EndEmpGetAllDataFields(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpGetAllDataFieldsResp)(results[0]));
        }
    }

    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmployerWebServiceV18Soap", Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmployerWebServiceV18 : System.Web.Services.Protocols.SoapHttpClientProtocol {

        /// <remarks/>
        public EmployerWebServiceV18() {
            this.Url = "https://test.vis-dhs.com/WebService/EmployerWebServiceV18.asmx";
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpInitBPVerif", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpInitVerfResp EmpInitBPVerif(
                    string ClientSftwrVer,
                    string LastName,
                    string FirstName,
                    string MiddleInitial,
                    string MaidenName,
                    string SSNNumber,
                    System.DateTime BirthDate,
                    System.DateTime HireDate,
                    int CitizenshipStatus,
                    string AlienNumber,
                    string I94Number,
                    string CardNbr,
                    string PassPortNumber,
                    string VisaNumber,
                    int DocumentID,
                    System.DateTime DocExpDate,
                    string SubmittingOfficial,
                    string SubmittersPhoneNbr,
                    string UserField) {
            object[] results = this.Invoke("EmpInitBPVerif", new object[] {
                        ClientSftwrVer,
                        LastName,
                        FirstName,
                        MiddleInitial,
                        MaidenName,
                        SSNNumber,
                        BirthDate,
                        HireDate,
                        CitizenshipStatus,
                        AlienNumber,
                        I94Number,
                        CardNbr,
                        PassPortNumber,
                        VisaNumber,
                        DocumentID,
                        DocExpDate,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        UserField});
            return ((EmpInitVerfResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpInitBPVerif(
                    string ClientSftwrVer,
                    string LastName,
                    string FirstName,
                    string MiddleInitial,
                    string MaidenName,
                    string SSNNumber,
                    System.DateTime BirthDate,
                    System.DateTime HireDate,
                    int CitizenshipStatus,
                    string AlienNumber,
                    string I94Number,
                    string CardNbr,
                    string PassPortNumber,
                    string VisaNumber,
                    int DocumentID,
                    System.DateTime DocExpDate,
                    string SubmittingOfficial,
                    string SubmittersPhoneNbr,
                    string UserField,
                    System.AsyncCallback callback,
                    object asyncState) {
            return this.BeginInvoke("EmpInitBPVerif", new object[] {
                        ClientSftwrVer,
                        LastName,
                        FirstName,
                        MiddleInitial,
                        MaidenName,
                        SSNNumber,
                        BirthDate,
                        HireDate,
                        CitizenshipStatus,
                        AlienNumber,
                        I94Number,
                        CardNbr,
                        PassPortNumber,
                        VisaNumber,
                        DocumentID,
                        DocExpDate,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        UserField}, callback, asyncState);
        }

        /// <remarks/>
        public EmpInitVerfResp EndEmpInitBPVerif(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpInitVerfResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpInitDABPVerif", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpInitVerfResp EmpInitDABPVerif(
                    int ClientCompanyId,
                    string ClientSftwrVer,
                    string LastName,
                    string FirstName,
                    string MiddleInitial,
                    string MaidenName,
                    string SSNNumber,
                    System.DateTime BirthDate,
                    System.DateTime HireDate,
                    int CitizenshipStatus,
                    string AlienNumber,
                    string I94Number,
                    string CardNbr,
                    string PassPortNumber,
                    string VisaNumber,
                    int DocumentID,
                    System.DateTime DocExpDate,
                    string SubmittingOfficial,
                    string SubmittersPhoneNbr,
                    string UserField) {
            object[] results = this.Invoke("EmpInitDABPVerif", new object[] {
                        ClientCompanyId,
                        ClientSftwrVer,
                        LastName,
                        FirstName,
                        MiddleInitial,
                        MaidenName,
                        SSNNumber,
                        BirthDate,
                        HireDate,
                        CitizenshipStatus,
                        AlienNumber,
                        I94Number,
                        CardNbr,
                        PassPortNumber,
                        VisaNumber,
                        DocumentID,
                        DocExpDate,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        UserField});
            return ((EmpInitVerfResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpInitDABPVerif(
                    int ClientCompanyId,
                    string ClientSftwrVer,
                    string LastName,
                    string FirstName,
                    string MiddleInitial,
                    string MaidenName,
                    string SSNNumber,
                    System.DateTime BirthDate,
                    System.DateTime HireDate,
                    int CitizenshipStatus,
                    string AlienNumber,
                    string I94Number,
                    string CardNbr,
                    string PassPortNumber,
                    string VisaNumber,
                    int DocumentID,
                    System.DateTime DocExpDate,
                    string SubmittingOfficial,
                    string SubmittersPhoneNbr,
                    string UserField,
                    System.AsyncCallback callback,
                    object asyncState) {
            return this.BeginInvoke("EmpInitDABPVerif", new object[] {
                        ClientCompanyId,
                        ClientSftwrVer,
                        LastName,
                        FirstName,
                        MiddleInitial,
                        MaidenName,
                        SSNNumber,
                        BirthDate,
                        HireDate,
                        CitizenshipStatus,
                        AlienNumber,
                        I94Number,
                        CardNbr,
                        PassPortNumber,
                        VisaNumber,
                        DocumentID,
                        DocExpDate,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        UserField}, callback, asyncState);
        }

        /// <remarks/>
        public EmpInitVerfResp EndEmpInitDABPVerif(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpInitVerfResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpSubmitAdditVerif", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpSubmitAdditVerifResp EmpSubmitAdditVerif(string ClientSftwrVer, string CaseNbr, string SubmittingOfficial, string SubmittersPhoneNbr, string Comment) {
            object[] results = this.Invoke("EmpSubmitAdditVerif", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        Comment});
            return ((EmpSubmitAdditVerifResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpSubmitAdditVerif(string ClientSftwrVer, string CaseNbr, string SubmittingOfficial, string SubmittersPhoneNbr, string Comment, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpSubmitAdditVerif", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        SubmittingOfficial,
                        SubmittersPhoneNbr,
                        Comment}, callback, asyncState);
        }

        /// <remarks/>
        public EmpSubmitAdditVerifResp EndEmpSubmitAdditVerif(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpSubmitAdditVerifResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpGetNextResolvedCaseNbrs", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpGetNextResolvedCaseNbrsResp EmpGetNextResolvedCaseNbrs(string ClientSftwrVer, string SearchType, string AcknowledgeFlg) {
            object[] results = this.Invoke("EmpGetNextResolvedCaseNbrs", new object[] {
                        ClientSftwrVer,
                        SearchType,
                        AcknowledgeFlg});
            return ((EmpGetNextResolvedCaseNbrsResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpGetNextResolvedCaseNbrs(string ClientSftwrVer, string SearchType, string AcknowledgeFlg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpGetNextResolvedCaseNbrs", new object[] {
                        ClientSftwrVer,
                        SearchType,
                        AcknowledgeFlg}, callback, asyncState);
        }

        /// <remarks/>
        public EmpGetNextResolvedCaseNbrsResp EndEmpGetNextResolvedCaseNbrs(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpGetNextResolvedCaseNbrsResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpAckReceiptOfResolvedCaseNbr", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpAckReceiptOfResolvedCaseNbrResp EmpAckReceiptOfResolvedCaseNbr(string ClientSftwrVer, string CaseNbr, string TypeOfCase) {
            object[] results = this.Invoke("EmpAckReceiptOfResolvedCaseNbr", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        TypeOfCase});
            return ((EmpAckReceiptOfResolvedCaseNbrResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpAckReceiptOfResolvedCaseNbr(string ClientSftwrVer, string CaseNbr, string TypeOfCase, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpAckReceiptOfResolvedCaseNbr", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        TypeOfCase}, callback, asyncState);
        }

        /// <remarks/>
        public EmpAckReceiptOfResolvedCaseNbrResp EndEmpAckReceiptOfResolvedCaseNbr(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpAckReceiptOfResolvedCaseNbrResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpCloseCase", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpCloseCaseResp EmpCloseCase(string ClientSftwrVer, string CaseNbr, string CloseStatus) {
            object[] results = this.Invoke("EmpCloseCase", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        CloseStatus});
            return ((EmpCloseCaseResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpCloseCase(string ClientSftwrVer, string CaseNbr, string CloseStatus, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpCloseCase", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        CloseStatus}, callback, asyncState);
        }

        /// <remarks/>
        public EmpCloseCaseResp EndEmpCloseCase(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpCloseCaseResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpSubSSAReferral", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpSubmitSSAReferralResp EmpSubSSAReferral(string ClientSftwrVer, string CaseNbr) {
            object[] results = this.Invoke("EmpSubSSAReferral", new object[] {
                        ClientSftwrVer,
                        CaseNbr});
            return ((EmpSubmitSSAReferralResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpSubSSAReferral(string ClientSftwrVer, string CaseNbr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpSubSSAReferral", new object[] {
                        ClientSftwrVer,
                        CaseNbr}, callback, asyncState);
        }

        /// <remarks/>
        public EmpSubmitSSAReferralResp EndEmpSubSSAReferral(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpSubmitSSAReferralResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpCpsVerifyConnection", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpCpsVerifyConnectionResp EmpCpsVerifyConnection() {
            object[] results = this.Invoke("EmpCpsVerifyConnection", new object[0]);
            return ((EmpCpsVerifyConnectionResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpCpsVerifyConnection(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpCpsVerifyConnection", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public EmpCpsVerifyConnectionResp EndEmpCpsVerifyConnection(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpCpsVerifyConnectionResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpSubDHSReferral", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpSubmitDHSReferralResp7 EmpSubDHSReferral(string ClientSftwrVer, string CaseNbr) {
            object[] results = this.Invoke("EmpSubDHSReferral", new object[] {
                        ClientSftwrVer,
                        CaseNbr});
            return ((EmpSubmitDHSReferralResp7)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpSubDHSReferral(string ClientSftwrVer, string CaseNbr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpSubDHSReferral", new object[] {
                        ClientSftwrVer,
                        CaseNbr}, callback, asyncState);
        }

        /// <remarks/>
        public EmpSubmitDHSReferralResp7 EndEmpSubDHSReferral(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpSubmitDHSReferralResp7)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/SetUserPassword", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetUserPasswordResp SetUserPassword(string NewPassword) {
            object[] results = this.Invoke("SetUserPassword", new object[] {
                        NewPassword});
            return ((SetUserPasswordResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSetUserPassword(string NewPassword, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetUserPassword", new object[] {
                        NewPassword}, callback, asyncState);
        }

        /// <remarks/>
        public SetUserPasswordResp EndSetUserPassword(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SetUserPasswordResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpSSAResubmittal", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpSSAResubmittalResp EmpSSAResubmittal(string ClientSftwrVer, string CaseNbr, string LastName, string FirstName, string MiddleNameInitial, string MaidenName, string SocialSecurityNbr, System.DateTime BirthDate) {
            object[] results = this.Invoke("EmpSSAResubmittal", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        LastName,
                        FirstName,
                        MiddleNameInitial,
                        MaidenName,
                        SocialSecurityNbr,
                        BirthDate});
            return ((EmpSSAResubmittalResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpSSAResubmittal(string ClientSftwrVer, string CaseNbr, string LastName, string FirstName, string MiddleNameInitial, string MaidenName, string SocialSecurityNbr, System.DateTime BirthDate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpSSAResubmittal", new object[] {
                        ClientSftwrVer,
                        CaseNbr,
                        LastName,
                        FirstName,
                        MiddleNameInitial,
                        MaidenName,
                        SocialSecurityNbr,
                        BirthDate}, callback, asyncState);
        }

        /// <remarks/>
        public EmpSSAResubmittalResp EndEmpSSAResubmittal(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpSSAResubmittalResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpGetCaseDetails", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpGtCseDetailsResp7 EmpGetCaseDetails(string CaseNbr) {
            object[] results = this.Invoke("EmpGetCaseDetails", new object[] {
                        CaseNbr});
            return ((EmpGtCseDetailsResp7)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpGetCaseDetails(string CaseNbr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpGetCaseDetails", new object[] {
                        CaseNbr}, callback, asyncState);
        }

        /// <remarks/>
        public EmpGtCseDetailsResp7 EndEmpGetCaseDetails(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpGtCseDetailsResp7)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpGetCitizenshipStatusCodes", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpGetCitizenshipCodesResp EmpGetCitizenshipStatusCodes() {
            object[] results = this.Invoke("EmpGetCitizenshipStatusCodes", new object[0]);
            return ((EmpGetCitizenshipCodesResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpGetCitizenshipStatusCodes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpGetCitizenshipStatusCodes", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public EmpGetCitizenshipCodesResp EndEmpGetCitizenshipStatusCodes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpGetCitizenshipCodesResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpGetAvailableDocumentTypes", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpGetAvailableDocumentTypesResp EmpGetAvailableDocumentTypes(string CitizenshipCode) {
            object[] results = this.Invoke("EmpGetAvailableDocumentTypes", new object[] {
                        CitizenshipCode});
            return ((EmpGetAvailableDocumentTypesResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpGetAvailableDocumentTypes(string CitizenshipCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpGetAvailableDocumentTypes", new object[] {
                        CitizenshipCode}, callback, asyncState);
        }

        /// <remarks/>
        public EmpGetAvailableDocumentTypesResp EndEmpGetAvailableDocumentTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpGetAvailableDocumentTypesResp)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.vis-dhs.com/EmployerWebService/EmpGetAllDataFields", RequestNamespace="https://www.vis-dhs.com/EmployerWebService/", ResponseNamespace="https://www.vis-dhs.com/EmployerWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmpGetAllDataFieldsResp EmpGetAllDataFields(string CitizenshipCode, string DocId) {
            object[] results = this.Invoke("EmpGetAllDataFields", new object[] {
                        CitizenshipCode,
                        DocId});
            return ((EmpGetAllDataFieldsResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEmpGetAllDataFields(string CitizenshipCode, string DocId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmpGetAllDataFields", new object[] {
                        CitizenshipCode,
                        DocId}, callback, asyncState);
        }

        /// <remarks/>
        public EmpGetAllDataFieldsResp EndEmpGetAllDataFields(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((EmpGetAllDataFieldsResp)(results[0]));
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpInitVerfResp {

        /// <remarks/>
        public string CaseNbr;

        /// <remarks/>
        public string LastName;

        /// <remarks/>
        public string FirstName;

        /// <remarks/>
        public string EligStatementCd;

        /// <remarks/>
        public string EligStatementTxt;

        /// <remarks/>
        public string EligStatementDetailsTxt;

        /// <remarks/>
        public string PotentialNaturalizedInd;

        /// <remarks/>
        public string AdditionalPerfind;

        /// <remarks/>
        public string PhotoIncluded;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public System.Byte[] Photo;

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class FieldListArray : IFieldListArray {

        /// <remarks/>
        public string DataElementName;

        /// <remarks/>
        public string RequiredInd;

        /// <remarks/>
        public string DocumentId;

        /// <remarks/>
        public string DocumentType;

        /// <remarks/>
        public string CitizenshipCode;

        /// <remarks/>
        public string CitizenshipName;

        // BEGIN: Added code to make Interface class work

        public string GetDataElementName() { return DataElementName; }
        public string GetRequiredInd() { return RequiredInd; }
        public string GetDocumentId() { return DocumentId; }
        public string GetDocumentType() { return DocumentType; }
        public string GetCitizenshipCode() { return CitizenshipCode; }
        public string GetCitizenshipName() { return CitizenshipName; }

        // END

    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpGetAllDataFieldsResp {

        /// <remarks/>
        public int NumberOfFieldRecords;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FieldListArray[] FieldArray;

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class DocTypeListArray : IDocTypeListArray {

        /// <remarks/>
        public string DocumentId;

        /// <remarks/>
        public string DocumentType;

        /// <remarks/>
        public string CitizenshipCode;

        /// <remarks/>
        public string CitizenshipName;

        // BEGIN: Added code to make Interface class work

        public string GetDocumentId() { return DocumentId; }
        public string GetDocumentType() { return DocumentType; }
        public string GetCitizenshipCode() { return CitizenshipCode; }
        public string GetCitizenshipName() { return CitizenshipName; }

        // END

    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpGetAvailableDocumentTypesResp {

        /// <remarks/>
        public int NumberOfDocTypes;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DocTypeListArray[] DocTypeArray;

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class CitizenshipCodeListArray : ICitizenshipCodeListArray {

        /// <remarks/>
        public string CitizenshipCode;

        /// <remarks/>
        public string CitizenshipDescr;

        /// <remarks/>
        public string CitizenshipName;

        // BEGIN: Added code to make Interface class work

        public string GetCitizenshipCode() { return CitizenshipCode; }
        public string GetCitizenshipDescription() { return CitizenshipDescr; }
        public string GetCitizenshipName() { return CitizenshipName; }

        // END

    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpGetCitizenshipCodesResp {

        /// <remarks/>
        public int NumberOfCitizenshipCodes;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CitizenshipCodeListArray[] CitizenshipCodeArray;

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpGtCseDetailsResp7 {

        /// <remarks/>
        public string CaseNbr;

        /// <remarks/>
        public string CurrentState;

        /// <remarks/>
        public string InitiCitizenshipDescr;

        /// <remarks/>
        public string InitiAlienNum;

        /// <remarks/>
        public string InitiI94Num;

        /// <remarks/>
        public string InitiLogonId;

        /// <remarks/>
        public System.DateTime InitiDt;

        /// <remarks/>
        public string InitiLastNm;

        /// <remarks/>
        public string InitiFirstNm;

        /// <remarks/>
        public string InitiMiddleInitial;

        /// <remarks/>
        public string InitiMaidenNm;

        /// <remarks/>
        public string InitiSsn;

        /// <remarks/>
        public System.DateTime InitiBirthDt;

        /// <remarks/>
        public System.DateTime InitiHireDt;

        /// <remarks/>
        public string InitiDocType;

        /// <remarks/>
        public System.DateTime InitiDocExpireDt;

        /// <remarks/>
        public string InitiUserField;

        /// <remarks/>
        public string InitoLastNm;

        /// <remarks/>
        public string InitoFirstNm;

        /// <remarks/>
        public string InitoMessageCode;

        /// <remarks/>
        public string InitoEligibStmt;

        /// <remarks/>
        public string InitoEligibStmtDetails;

        /// <remarks/>
        public string PotentialNaturalizedInd;

        /// <remarks/>
        public string AddiiComments;

        /// <remarks/>
        public string AddiiLogonId;

        /// <remarks/>
        public System.DateTime AddiiDt;

        /// <remarks/>
        public string AddiiTransCd;

        /// <remarks/>
        public string AddioEligibStmt;

        /// <remarks/>
        public string AddioResolutionCode;

        /// <remarks/>
        public System.DateTime AddioResolvedDt;

        /// <remarks/>
        public string ClosureCdDescr;

        /// <remarks/>
        public string ClosedBy;

        /// <remarks/>
        public System.DateTime ClosedDt;

        /// <remarks/>
        public System.DateTime InsReferiDt;

        /// <remarks/>
        public string InsReferiBy;

        /// <remarks/>
        public string InsReferoEligibStmt;

        /// <remarks/>
        public string InsReferoResolutionCode;

        /// <remarks/>
        public System.DateTime InsReferoResolvedDt;

        /// <remarks/>
        public System.DateTime InsReferoContactDHSByDt;

        /// <remarks/>
        public System.DateTime SsaReferiDt;

        /// <remarks/>
        public string SsaReferiBy;

        /// <remarks/>
        public string SsaResubmiLastNm;

        /// <remarks/>
        public string SsaResubmiFirstNm;

        /// <remarks/>
        public string SsaResubmiMiddleInitial;

        /// <remarks/>
        public string SsaResubmiMaidenNm;

        /// <remarks/>
        public string SsaResubmiSsn;

        /// <remarks/>
        public System.DateTime SsaResubmiBirthDt;

        /// <remarks/>
        public string SsaResubmiLogonId;

        /// <remarks/>
        public System.DateTime SsaResubmiDt;

        /// <remarks/>
        public string SsaResubmoMessageCode;

        /// <remarks/>
        public string SsaResubmoEligibStmt;

        /// <remarks/>
        public System.DateTime SsaReferralRespDueDate;

        /// <remarks/>
        public string ClientCompanyName;

        /// <remarks/>
        public string PhotoIncluded;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public System.Byte[] Photo;

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpSSAResubmittalResp {

        /// <remarks/>
        public string LastName;

        /// <remarks/>
        public string FirstName;

        /// <remarks/>
        public string EligStatementCd;

        /// <remarks/>
        public string EligStatementTxt;

        /// <remarks/>
        public string AdditionalPerfind;

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class SetUserPasswordResp {

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpSubmitDHSReferralResp7 {

        /// <remarks/>
        public System.DateTime ContactDHSByDt;

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpCpsVerifyConnectionResp {

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpSubmitSSAReferralResp {

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpCloseCaseResp {

        /// <remarks/>
        public string UserField;

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpAckReceiptOfResolvedCaseNbrResp {

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class CaseListArray : ICaseListArray {

        /// <remarks/>
        public string CaseNbr;

        /// <remarks/>
        public string TypeOfCase;

        /// <remarks/>
        public string UserField;

        /// <remarks/>
        public string ResponseCode;

        /// <remarks/>
        public string ResponseStmt;

        /// <remarks/>
        public System.DateTime ResolveDate;

        // BEGIN: Added code to make Interface class work

        public string GetCaseNumber() { return CaseNbr; }
        public string GetTypeOfCase() { return TypeOfCase; }
        public string GetUserField() { return UserField; }
        public string GetResponseCode() { return ResponseCode; }
        public string GetResponseStatement() { return ResponseStmt; }

        public System.DateTime GetResolveDate() { return ResolveDate; }

        // END

    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpGetNextResolvedCaseNbrsResp {

        /// <remarks/>
        public int NumberOfCases;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CaseListArray[] CaseArray;

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.vis-dhs.com/EmployerWebService/")]
    public class EmpSubmitAdditVerifResp {

        /// <remarks/>
        public int ReturnStatus;

        /// <remarks/>
        public string ReturnStatusMsg;
    }
}
